PREPARE RESUMEN_EJECUCION_OFICIAL FROM

SELECT 

    A.VCHCARTERA,

    A.NUMFECHAREFERENCIA,

    A.NUMSTAGE AS STAGE,

    CASE 

    WHEN A.VCHMOTIVOSTAGING = '1.001 Sin Motivo' AND TRY_CAST(A.NUMDIASVENCIDO AS DOUBLE) <= 8 THEN ' 1.001 Sin Motivo-8 a menos'

    WHEN A.VCHMOTIVOSTAGING = '1.001 Sin Motivo' AND TRY_CAST(A.NUMDIASVENCIDO AS DOUBLE) > 8 THEN ' 1.001 Sin Motivo-9 a mas'

    WHEN A.VCHMOTIVOSTAGING = '2.001 Incremento significativo de PD' AND TRY_CAST(A.NUMDIASVENCIDO AS DOUBLE) <= 8 THEN ' 2.001 ISR-8 menos'

    WHEN A.VCHMOTIVOSTAGING = '2.001 Incremento significativo de PD' AND TRY_CAST(A.NUMDIASVENCIDO AS DOUBLE) > 8 THEN ' 2.001 ISR-9 a mas'

    WHEN A.VCHMOTIVOSTAGING = '2.002 Missing PD' THEN ' 2.002 Missing PD'

    ELSE A.VCHMOTIVOSTAGING

    END AS MOTIVOS,

    SUM(TRY_CAST(A.NUMEAD AS DOUBLE)) AS EAD,

    SUM(TRY_CAST(A.NUMEAD AS DOUBLE) * TRY_CAST(A.NUMRATIODIRECTO AS DOUBLE)) AS SALDO_DIRECTO,

    SUM(TRY_CAST(A.NUMEAD AS DOUBLE) * TRY_CAST(A.NUMLGD AS DOUBLE)) AS EAD_LGD,

    SUM(? * TRY_CAST(A.NUMPROVISIONIFRS9 AS DOUBLE) + /*BASE*/

        ? * TRY_CAST(B.NUMPROVISIONIFRS9 AS DOUBLE) + /*PESIMISTA*/

        ? * TRY_CAST(C.NUMPROVISIONIFRS9 AS DOUBLE))  /*OPTIMISTA*/

        as PROVISION,

    SUM(? * TRY_CAST(A.NUMPEAJUSTEFINAL AS DOUBLE) /*BASE*/

      + ? * TRY_CAST(B.NUMPEAJUSTEFINAL AS DOUBLE) /*PESIMISTA*/

      + ? * TRY_CAST(C.NUMPEAJUSTEFINAL AS DOUBLE)) /*OPTIMISTA*/

      as PROVISION_REACTIVA

	FROM 

	    (SELECT * FROM e_ifrs_discovery.hoa_outputprovisionescred WHERE NUMCODEJECUCION IN (?)) A  /*BASE*/

	LEFT JOIN 

	    (SELECT * FROM e_ifrs_discovery.hoa_outputprovisionescred WHERE NUMCODEJECUCION IN (?)) B  /*PESIMISTA*/

	    ON A.VCHCONCATENADO = B.VCHCONCATENADO  AND A.NUMMARCAREVOLVENTE = B.NUMMARCAREVOLVENTE

	LEFT JOIN 

	    (SELECT * FROM e_ifrs_discovery.hoa_outputprovisionescred WHERE NUMCODEJECUCION IN (?)) C /*OPTIMISTA*/

	    ON A.VCHCONCATENADO = C.VCHCONCATENADO AND A.NUMMARCAREVOLVENTE = C.NUMMARCAREVOLVENTE

	GROUP BY 1,2,3,4

	ORDER BY 1,2,3,4

